/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Control.ControlCategorias;
import Control.ControlCliente;
import Control.ControlProductos;
import Control.ControlProveedores;
import Control.ControlVenta;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.Categoria;
import objetosNegocio.Cliente;
import objetosNegocio.Producto;
import objetosNegocio.Proveedor;
import objetosNegocio.Venta;

/**
 *
 * @author miran
 */
public class FrmCliente extends javax.swing.JFrame {

    private ControlCategorias controlCategorias;
    private ControlProveedores controlProveedores;
    private ControlCliente controlClientes;
    private ControlVenta controlVentas;
    private ControlProductos controlProductos;
    List<Cliente> listaClientes;

    /**
     * Creates new form FrmClient
     */
    public FrmCliente() {
        initComponents();
        this.setTitle("FrmCliente");
        this.setLocationRelativeTo(null);
        this.controlProveedores = new ControlProveedores();
        this.controlCategorias = new ControlCategorias();
        this.controlClientes = new ControlCliente();
        this.controlVentas = new ControlVenta();
        this.controlProductos = new ControlProductos();
        this.listaClientes = new ArrayList<>();
        this.quitarAdvertencias();
        this.limpiarCampos();
        this.llenarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblp = new javax.swing.JLabel();
        producto = new javax.swing.JLabel();
        lblpro = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        lblcat = new javax.swing.JLabel();
        venta = new javax.swing.JLabel();
        lblv = new javax.swing.JLabel();
        registro = new javax.swing.JLabel();
        lblrv = new javax.swing.JLabel();
        proveedor = new javax.swing.JLabel();
        lblrv1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtTelefono2 = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        lblp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblp.setForeground(new java.awt.Color(102, 102, 102));
        lblp.setText("Proveedores");
        lblp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpMouseExited(evt);
            }
        });

        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canasta72.png"))); // NOI18N
        producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productoMouseExited(evt);
            }
        });

        lblpro.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblpro.setForeground(new java.awt.Color(102, 102, 102));
        lblpro.setText("Productos");
        lblpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblproMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblproMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblproMouseExited(evt);
            }
        });

        categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tomate72.png"))); // NOI18N
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriaMouseExited(evt);
            }
        });

        lblcat.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblcat.setForeground(new java.awt.Color(102, 102, 102));
        lblcat.setText("Categorias");
        lblcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcatMouseExited(evt);
            }
        });

        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket72.png"))); // NOI18N
        venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventaMouseExited(evt);
            }
        });

        lblv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblv.setForeground(new java.awt.Color(102, 102, 102));
        lblv.setText("Ventas");
        lblv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvMouseExited(evt);
            }
        });

        registro.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito72.png"))); // NOI18N
        registro.setToolTipText("");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registroMousePressed(evt);
            }
        });

        lblrv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv.setForeground(new java.awt.Color(102, 102, 102));
        lblrv.setText("Registro");
        lblrv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrvMouseExited(evt);
            }
        });

        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion72.png"))); // NOI18N
        proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedorMouseExited(evt);
            }
        });

        lblrv1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv1.setForeground(new java.awt.Color(102, 102, 102));
        lblrv1.setText("de ventas");
        lblrv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrv1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrv1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(producto)
                            .addComponent(categoria)
                            .addComponent(lblcat)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblrv1)
                                .addComponent(lblrv)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblv)
                                    .addComponent(venta)
                                    .addComponent(registro)))
                            .addComponent(lblpro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(proveedor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblp)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblp)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpro)
                .addGap(18, 18, 18)
                .addComponent(categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcat)
                .addGap(18, 18, 18)
                .addComponent(venta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblv)
                .addGap(18, 18, 18)
                .addComponent(registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv1)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));
        jPanel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel6PropertyChange(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtRfc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RFC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcKeyTyped(evt);
            }
        });

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtTelefono2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teléfono 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtTelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono2KeyTyped(evt);
            }
        });

        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        lblDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        lblRfc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRfc, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(txtId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRfc)))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(lblNombre))
                .addGap(83, 83, 83))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRfc))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupaRosa.png"))); // NOI18N

        txtBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btAceptar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btAceptar.setForeground(new java.awt.Color(102, 102, 102));
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btEditar.setForeground(new java.awt.Color(102, 102, 102));
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btEliminar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btEliminar.setForeground(new java.awt.Color(102, 102, 102));
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "RFC", "Nombre", "Dirección", "Teléfono", "Teléfono 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homeBlanco.png"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblpMouseEntered

    private void lblpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblpMouseExited

    private void productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseEntered
        producto.setIcon(new ImageIcon("imagenes\\canasta72n.png"));
        lblpro.setForeground(Color.BLACK);
    }//GEN-LAST:event_productoMouseEntered

    private void productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseExited
        producto.setIcon(new ImageIcon("imagenes\\canasta72.png"));
        lblpro.setForeground(Color.GRAY);
    }//GEN-LAST:event_productoMouseExited

    private void lblproMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseEntered
        producto.setIcon(new ImageIcon("imagenes\\canasta72n.png"));
        lblpro.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblproMouseEntered

    private void lblproMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseExited
        producto.setIcon(new ImageIcon("imagenes\\canasta72.png"));
        lblpro.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblproMouseExited

    private void categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\tomate72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_categoriaMouseEntered

    private void categoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\tomate72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_categoriaMouseExited

    private void lblcatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\tomate72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblcatMouseEntered

    private void lblcatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\tomate72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblcatMouseExited

    private void ventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseEntered
        venta.setIcon(new ImageIcon("imagenes\\ticket72n.png"));
        lblv.setForeground(Color.BLACK);
    }//GEN-LAST:event_ventaMouseEntered

    private void ventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseExited
        venta.setIcon(new ImageIcon("imagenes\\ticket72.png"));
        lblv.setForeground(Color.GRAY);
    }//GEN-LAST:event_ventaMouseExited

    private void lblvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseEntered
        venta.setIcon(new ImageIcon("imagenes\\ticket72n.png"));
        lblv.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblvMouseEntered

    private void lblvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseExited
        venta.setIcon(new ImageIcon("imagenes\\ticket72.png"));
        lblv.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblvMouseExited

    private void registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_registroMouseEntered

    private void registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_registroMouseExited

    private void registroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMousePressed

    }//GEN-LAST:event_registroMousePressed

    private void lblrvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrvMouseEntered

    private void lblrvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrvMouseExited

    private void proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_proveedorMouseEntered

    private void proveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_proveedorMouseExited

    private void lblrv1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrv1MouseEntered

    private void lblrv1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrv1MouseExited

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void jPanel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6PropertyChange

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        FrmInicio menu = new FrmInicio();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
          x.setIcon(new ImageIcon("imagenes\\homeNegro.png"));
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
          x.setIcon(new ImageIcon("imagenes\\homeBlanco.png"));
    }//GEN-LAST:event_xMouseExited

    private void xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKeyPressed

    }//GEN-LAST:event_xKeyPressed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        if (this.txtId.getText().isEmpty() || this.txtId.getText().equals("")) {
            this.guardarCliente();
        } else {
            this.actualizarCliente();
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        this.buscarLike();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        this.cargarCliente();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        this.eliminarCliente();
    }//GEN-LAST:event_btEliminarActionPerformed

    private void proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_proveedorMouseClicked

    private void lblpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_lblpMouseClicked

    private void productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_productoMouseClicked

    private void lblproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedorregistrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblproMouseClicked

    private void categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_categoriaMouseClicked

    private void lblcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblcatMouseClicked

    private void ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ventaMouseClicked

    private void lblvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblvMouseClicked

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_registroMouseClicked

    private void lblrvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrvMouseClicked

    private void lblrv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrv1MouseClicked

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if (txtTelefono.getText().length() == 10) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono2KeyTyped
        if (txtTelefono2.getText().length() == 10) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefono2KeyTyped

    private void txtRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcKeyTyped
        if (txtRfc.getText().length() == 15) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            if (!Character.isLetter(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtRfcKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() == 45) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        if (txtDireccion.getText().length() == 100) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
          if (txtBusqueda.getText().length() == 15) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            if (!Character.isLetter(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private boolean hayProducto() {
        List<Producto> listaProductos = controlProductos.buscarTodas("");
        if (listaProductos.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayVenta() {
        List<Venta> listaVentas = controlVentas.buscarTodas("");
        if (listaVentas.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayProveedor() {
        List<Proveedor> listaProveedores = controlProveedores.buscarTodas("");
        if (listaProveedores.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCliente() {
        List<Cliente> listaClientes = controlClientes.buscarTodas("");
        if (listaClientes.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCategoria() {
        List<Categoria> listaCategoria = controlCategorias.buscarTodas("");
        if (listaCategoria.isEmpty()) {
            return true;
        }
        return false;
    }

    private void guardarCliente() {
        if (!camposVacios()) {
            String rfc = this.txtRfc.getText();
            String nombre = this.txtNombre.getText();
            String direccion = this.txtDireccion.getText();
            String telefono = this.txtTelefono.getText();
            String telefono2 = this.txtTelefono2.getText();
            Cliente cliente = new Cliente(rfc, nombre, direccion, telefono, telefono2);
            if (controlClientes.guardar(cliente)) {
                JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                this.limpiarCampos();
                this.llenarTablaClientes();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el cliente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos deben de estar llenos.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void actualizarCliente() {
        if (!camposVacios()) {
            int id = Integer.parseInt(this.txtId.getText());
            String rfc = this.txtRfc.getText();
            String nombre = this.txtNombre.getText();
            String direccion = this.txtDireccion.getText();
            String telefono = this.txtTelefono.getText();
            String telefono2 = this.txtTelefono2.getText();
            Cliente cliente = new Cliente(id, rfc, nombre, direccion, telefono, telefono2);
            if (controlClientes.actualizar(cliente)) {
                JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                this.limpiarCampos();
                this.llenarTablaClientes();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el cliente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos deben de estar llenos.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void eliminarCliente() {
        int fila = this.tblClientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblClientes.getModel();
            Integer idCliente = (Integer) modelo.getValueAt(fila, 0);
            if (controlClientes.eliminar(idCliente)) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                this.llenarTablaClientes();
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se logro eliminar al cliente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void llenarTablaClientes() {
        String busqueda = txtBusqueda.getText();
        listaClientes = controlClientes.buscarTodas(busqueda);
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
        for (Cliente cliente : listaClientes) {
            modelo.addRow(cliente.toArray());
        }
    }

    private void cargarCliente() {
        int fila = this.tblClientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblClientes.getModel();
            Integer idCliente = (Integer) modelo.getValueAt(fila, 0);
            Cliente cliente = controlClientes.buscarporID(idCliente);
            if (cliente != null) {
                this.txtId.setText(String.valueOf(cliente.getIdcliente()));
                this.txtRfc.setText(cliente.getRfc());
                this.txtNombre.setText(cliente.getNombre());
                this.txtDireccion.setText(cliente.getDireccion());
                this.txtTelefono.setText(cliente.getTelefono1());
                this.txtTelefono2.setText(cliente.getTelefono2());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el cliente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void buscarLike() {
        String Busqueda = txtBusqueda.getText();
        listaClientes = controlClientes.buscarLike(Busqueda);
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
        for (Cliente cliente : listaClientes) {
            modelo.addRow(cliente.toArray());
        }
    }

    private boolean camposVacios() {
        boolean hayVacios = false;
        if (this.txtRfc.getText().isEmpty() || this.txtRfc.getText().equals("")) {
            this.lblRfc.setVisible(true);
            hayVacios = true;
        } else {
            this.lblRfc.setVisible(false);
        }
        if (this.txtNombre.getText().isEmpty() || this.txtNombre.getText().equals("")) {
            this.lblNombre.setVisible(true);
            hayVacios = true;
        } else {
            this.lblNombre.setVisible(false);
        }
        if (this.txtDireccion.getText().isEmpty() || this.txtDireccion.getText().equals("")) {
            this.lblDireccion.setVisible(true);
            hayVacios = true;
        } else {
            this.lblDireccion.setVisible(false);
        }
        return hayVacios;
    }

    private void quitarAdvertencias() {
        this.lblRfc.setVisible(false);
        this.lblNombre.setVisible(false);
        this.lblDireccion.setVisible(false);
    }

    private void limpiarCampos() {
        this.txtId.setText("");
        this.txtRfc.setText("");
        this.txtNombre.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.txtTelefono2.setText("");
        this.txtBusqueda.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblcat;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel lblpro;
    private javax.swing.JLabel lblrv;
    private javax.swing.JLabel lblrv1;
    private javax.swing.JLabel lblv;
    private javax.swing.JLabel producto;
    private javax.swing.JLabel proveedor;
    private javax.swing.JLabel registro;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JLabel venta;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
