/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Control.ControlCategorias;
import Control.ControlCliente;
import Control.ControlProductos;
import Control.ControlProveedores;
import Control.ControlVenta;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetosNegocio.Categoria;
import objetosNegocio.Cliente;
import objetosNegocio.Producto;
import objetosNegocio.Proveedor;
import objetosNegocio.Venta;

/**
 *
 * @author miran
 */
public class FrmInicio extends javax.swing.JFrame {

    private ControlProveedores controlProveedores;
    private ControlCategorias controlCategorias;
    private ControlCliente controlClientes;
    private ControlVenta controlVentas;
    private ControlProductos controlProductos;

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setTitle("FrmInicio");
        this.setLocationRelativeTo(null);
        this.controlProveedores = new ControlProveedores();
        this.controlCategorias = new ControlCategorias();
        this.controlClientes = new ControlCliente();
        this.controlVentas = new ControlVenta();
        this.controlProductos = new ControlProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        proveedores = new javax.swing.JLabel();
        clientes = new javax.swing.JLabel();
        categorias = new javax.swing.JLabel();
        v = new javax.swing.JLabel();
        ventas = new javax.swing.JLabel();
        rv = new javax.swing.JLabel();
        regv = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        productos = new javax.swing.JLabel();
        pez = new javax.swing.JLabel();
        botella = new javax.swing.JLabel();
        tomatito = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(153, 0, 102));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion.png"))); // NOI18N
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p1MouseExited(evt);
            }
        });

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c1.png"))); // NOI18N
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1MouseExited(evt);
            }
        });

        proveedores.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        proveedores.setForeground(new java.awt.Color(102, 102, 102));
        proveedores.setText("Proveedores");
        proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedoresMouseExited(evt);
            }
        });

        clientes.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        clientes.setForeground(new java.awt.Color(102, 102, 102));
        clientes.setText("Clientes");
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesMouseExited(evt);
            }
        });

        categorias.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        categorias.setForeground(new java.awt.Color(102, 102, 102));
        categorias.setText("Categorías");
        categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriasMouseExited(evt);
            }
        });

        v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t2.png"))); // NOI18N
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vMouseExited(evt);
            }
        });

        ventas.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ventas.setForeground(new java.awt.Color(102, 102, 102));
        ventas.setText("Ventas");
        ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventasMouseExited(evt);
            }
        });

        rv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        rv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rvMouseExited(evt);
            }
        });

        regv.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        regv.setForeground(new java.awt.Color(102, 102, 102));
        regv.setText("Registro de ventas");
        regv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regvMouseExited(evt);
            }
        });

        p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pro.png"))); // NOI18N
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMouseExited(evt);
            }
        });

        productos.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        productos.setForeground(new java.awt.Color(102, 102, 102));
        productos.setText("Productos");
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productosMouseExited(evt);
            }
        });

        pez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pescadito.png"))); // NOI18N
        pez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pezMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pezMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pezMouseExited(evt);
            }
        });

        botella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botella.png"))); // NOI18N
        botella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botellaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botellaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botellaMouseExited(evt);
            }
        });

        tomatito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tomate.png"))); // NOI18N
        tomatito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tomatitoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tomatitoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tomatitoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(pez)
                                .addGap(44, 44, 44)
                                .addComponent(tomatito))
                            .addComponent(p1)
                            .addComponent(proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(categorias))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(botella)))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(clientes)
                                .addGap(179, 179, 179))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rv)
                                    .addComponent(c1))
                                .addGap(156, 156, 156)))
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(productos))
                            .addComponent(p)
                            .addComponent(v))
                        .addGap(75, 75, 75))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(regv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(ventas)
                        .addGap(99, 99, 99))))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1)
                            .addComponent(p))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientes)
                        .addComponent(proveedores))
                    .addComponent(productos))
                .addGap(117, 117, 117)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rv)
                            .addComponent(v))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regv)
                            .addComponent(ventas)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(botella)
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pez)
                            .addComponent(tomatito))
                        .addGap(18, 18, 18)
                        .addComponent(categorias)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x2.png"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menú");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Infob.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(340, 340, 340)
                .addComponent(x)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Panel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(x))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseExited
        p1.setIcon(new ImageIcon("imagenes\\camion.png"));
        proveedores.setForeground(Color.GRAY);
    }//GEN-LAST:event_proveedoresMouseExited

    private void proveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseEntered
        p1.setIcon(new ImageIcon("imagenes\\camn.png"));
        proveedores.setForeground(Color.BLACK);
    }//GEN-LAST:event_proveedoresMouseEntered

    private void clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseEntered
        c1.setIcon(new ImageIcon("imagenes\\cn.png"));
        clientes.setForeground(Color.BLACK);
    }//GEN-LAST:event_clientesMouseEntered

    private void clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseExited
        c1.setIcon(new ImageIcon("imagenes\\c1.png"));
        clientes.setForeground(Color.GRAY);
    }//GEN-LAST:event_clientesMouseExited

    private void productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseEntered
        p.setIcon(new ImageIcon("imagenes\\productosn.png"));
        productos.setForeground(Color.BLACK);
    }//GEN-LAST:event_productosMouseEntered

    private void productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseExited
        p.setIcon(new ImageIcon("imagenes\\pro.png"));
        productos.setForeground(Color.GRAY);
    }//GEN-LAST:event_productosMouseExited

    private void categoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasMouseEntered
        botella.setIcon(new ImageIcon("imagenes\\bn.png"));
        pez.setIcon(new ImageIcon("imagenes\\pezn.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\ton.png"));
        categorias.setForeground(Color.BLACK);
    }//GEN-LAST:event_categoriasMouseEntered

    private void categoriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasMouseExited
        botella.setIcon(new ImageIcon("imagenes\\botella.png"));
        pez.setIcon(new ImageIcon("imagenes\\pescadito.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\tomate.png"));
        categorias.setForeground(Color.GRAY);
    }//GEN-LAST:event_categoriasMouseExited

    private void regvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regvMouseEntered
        rv.setIcon(new ImageIcon("imagenes\\cne.png"));
        regv.setForeground(Color.BLACK);
    }//GEN-LAST:event_regvMouseEntered

    private void regvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regvMouseExited
        rv.setIcon(new ImageIcon("imagenes\\carrito.png"));
        regv.setForeground(Color.GRAY);
    }//GEN-LAST:event_regvMouseExited

    private void ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseEntered
        v.setIcon(new ImageIcon("imagenes\\tn.png"));
        ventas.setForeground(Color.BLACK);
    }//GEN-LAST:event_ventasMouseEntered

    private void ventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseExited
        v.setIcon(new ImageIcon("imagenes\\t2.png"));
        ventas.setForeground(Color.GRAY);
    }//GEN-LAST:event_ventasMouseExited

    private void xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKeyPressed

    }//GEN-LAST:event_xKeyPressed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        int salir = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "¡¡Atención!!", JOptionPane.WARNING_MESSAGE);
        if (salir == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_xMouseClicked

    private void c1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseEntered
        c1.setIcon(new ImageIcon("imagenes\\cn.png"));
        clientes.setForeground(Color.BLACK);
    }//GEN-LAST:event_c1MouseEntered

    private void c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseExited
        c1.setIcon(new ImageIcon("imagenes\\c1.png"));
        clientes.setForeground(Color.GRAY);
    }//GEN-LAST:event_c1MouseExited

    private void p1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseEntered
        p1.setIcon(new ImageIcon("imagenes\\camn.png"));
        proveedores.setForeground(Color.BLACK);
    }//GEN-LAST:event_p1MouseEntered

    private void p1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseExited
        p1.setIcon(new ImageIcon("imagenes\\camion.png"));
        proveedores.setForeground(Color.GRAY);
    }//GEN-LAST:event_p1MouseExited

    private void pMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseEntered
        p.setIcon(new ImageIcon("imagenes\\productosn.png"));
        productos.setForeground(Color.BLACK);
    }//GEN-LAST:event_pMouseEntered

    private void pMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseExited
        p.setIcon(new ImageIcon("imagenes\\pro.png"));
        productos.setForeground(Color.GRAY);
    }//GEN-LAST:event_pMouseExited

    private void rvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseEntered
        rv.setIcon(new ImageIcon("imagenes\\cne.png"));
        regv.setForeground(Color.BLACK);
    }//GEN-LAST:event_rvMouseEntered

    private void rvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseExited
        rv.setIcon(new ImageIcon("imagenes\\carrito.png"));
        regv.setForeground(Color.GRAY);
    }//GEN-LAST:event_rvMouseExited

    private void vMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseEntered
        v.setIcon(new ImageIcon("imagenes\\tn.png"));
        ventas.setForeground(Color.BLACK);
    }//GEN-LAST:event_vMouseEntered

    private void vMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseExited
        v.setIcon(new ImageIcon("imagenes\\t2.png"));
        ventas.setForeground(Color.GRAY);
    }//GEN-LAST:event_vMouseExited

    private void botellaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botellaMouseEntered
        botella.setIcon(new ImageIcon("imagenes\\bn.png"));
        pez.setIcon(new ImageIcon("imagenes\\pezn.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\ton.png"));
        categorias.setForeground(Color.BLACK);
    }//GEN-LAST:event_botellaMouseEntered

    private void pezMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pezMouseEntered
        botella.setIcon(new ImageIcon("imagenes\\bn.png"));
        pez.setIcon(new ImageIcon("imagenes\\pezn.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\ton.png"));
        categorias.setForeground(Color.BLACK);
    }//GEN-LAST:event_pezMouseEntered

    private void tomatitoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomatitoMouseEntered
        botella.setIcon(new ImageIcon("imagenes\\bn.png"));
        pez.setIcon(new ImageIcon("imagenes\\pezn.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\ton.png"));
        categorias.setForeground(Color.BLACK);
    }//GEN-LAST:event_tomatitoMouseEntered

    private void pezMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pezMouseExited
        botella.setIcon(new ImageIcon("imagenes\\botella.png"));
        pez.setIcon(new ImageIcon("imagenes\\pescadito.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\tomate.png"));
        categorias.setForeground(Color.GRAY);
    }//GEN-LAST:event_pezMouseExited

    private void botellaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botellaMouseExited
        botella.setIcon(new ImageIcon("imagenes\\botella.png"));
        pez.setIcon(new ImageIcon("imagenes\\pescadito.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\tomate.png"));
        categorias.setForeground(Color.GRAY);
    }//GEN-LAST:event_botellaMouseExited

    private void tomatitoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomatitoMouseExited
        botella.setIcon(new ImageIcon("imagenes\\botella.png"));
        pez.setIcon(new ImageIcon("imagenes\\pescadito.png"));
        tomatito.setIcon(new ImageIcon("imagenes\\tomate.png"));
        categorias.setForeground(Color.GRAY);
    }//GEN-LAST:event_tomatitoMouseExited

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x.setIcon(new ImageIcon("imagenes\\xn.png"));
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x.setIcon(new ImageIcon("imagenes\\x2.png"));
    }//GEN-LAST:event_xMouseExited

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_p1MouseClicked

    private void proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_proveedoresMouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_c1MouseClicked

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_clientesMouseClicked

    private void pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_pMouseClicked

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_productosMouseClicked

    private void botellaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botellaMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botellaMouseClicked

    private void pezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pezMouseClicked
       if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_pezMouseClicked

    private void tomatitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomatitoMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tomatitoMouseClicked

    private void categoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasMouseClicked
     if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_categoriasMouseClicked

    private void rvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rvMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rvMouseClicked

    private void regvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regvMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_regvMouseClicked

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_vMouseClicked

    private void ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ventasMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new ImageIcon("imagenes\\infon.png"));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       jLabel1.setIcon(new ImageIcon("imagenes\\infob.png"));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JOptionPane.showMessageDialog(this, "By: Fernanda Miranda - Daniel Trinidad", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel1MouseClicked

    private boolean hayProducto() {
        List<Producto> listaProductos = controlProductos.buscarTodas("");
        if (listaProductos.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayVenta() {
        List<Venta> listaVentas = controlVentas.buscarTodas("");
        if (listaVentas.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayProveedor() {
        List<Proveedor> listaProveedores = controlProveedores.buscarTodas("");
        if (listaProveedores.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCliente() {
        List<Cliente> listaClientes = controlClientes.buscarTodas("");
        if (listaClientes.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCategoria() {
        List<Categoria> listaCategoria = controlCategorias.buscarTodas("");
        if (listaCategoria.isEmpty()) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel botella;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel categorias;
    private javax.swing.JLabel clientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel p;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel pez;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel proveedores;
    private javax.swing.JLabel regv;
    private javax.swing.JLabel rv;
    private javax.swing.JLabel tomatito;
    private javax.swing.JLabel v;
    private javax.swing.JLabel ventas;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
