/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetosNegocio.Proveedor;
import objetosNegocio.Categoria;
import Control.ControlCategorias;
import Control.ControlCliente;
import Control.ControlProductos;
import Control.ControlProveedores;
import Control.ControlVenta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.Cliente;
import objetosNegocio.Producto;
import objetosNegocio.Venta;

/**
 *
 * @author miran
 */
public class FrmProducto extends javax.swing.JFrame {

    private ControlCategorias controlCategorias;
    private ControlProductos controlProductos;
    private ControlProveedores controlProveedores;
    private ControlCliente controlClientes;
    private ControlVenta controlVentas;
    List<Producto> listaProductos;

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
        this.setTitle("FrmProducto");
        this.setLocationRelativeTo(null);
        this.controlProveedores = new ControlProveedores();
        this.controlCategorias = new ControlCategorias();
        this.controlClientes = new ControlCliente();
        this.controlVentas = new ControlVenta();
        this.controlProductos = new ControlProductos();
        this.listaProductos = new ArrayList<>();
        this.quitarAdvertencias();
        this.llenarCboxProveedores();
        this.llenarCboxCategorias();
        this.limpiarCampos();
        this.llenarTablasProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblp = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        lbcliente = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        lblcat = new javax.swing.JLabel();
        venta = new javax.swing.JLabel();
        lblv = new javax.swing.JLabel();
        registro = new javax.swing.JLabel();
        lblrv = new javax.swing.JLabel();
        proveedor = new javax.swing.JLabel();
        lblrv1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecioActual = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblPrecioActual = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblCboxCategoria = new javax.swing.JLabel();
        cboxCategorias = new javax.swing.JComboBox<>();
        cboxProveedores = new javax.swing.JComboBox<>();
        lblCboxProveedor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        lblp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblp.setForeground(new java.awt.Color(102, 102, 102));
        lblp.setText("Proveedores");
        lblp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpMouseExited(evt);
            }
        });

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes72.png"))); // NOI18N
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteMouseExited(evt);
            }
        });

        lbcliente.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbcliente.setForeground(new java.awt.Color(102, 102, 102));
        lbcliente.setText("Clientes");
        lbcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbclienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbclienteMouseExited(evt);
            }
        });

        categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botella72.png"))); // NOI18N
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriaMouseExited(evt);
            }
        });

        lblcat.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblcat.setForeground(new java.awt.Color(102, 102, 102));
        lblcat.setText("Categorias");
        lblcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcatMouseExited(evt);
            }
        });

        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket72.png"))); // NOI18N
        venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventaMouseExited(evt);
            }
        });

        lblv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblv.setForeground(new java.awt.Color(102, 102, 102));
        lblv.setText("Ventas");
        lblv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblvMouseExited(evt);
            }
        });

        registro.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito72.png"))); // NOI18N
        registro.setToolTipText("");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registroMousePressed(evt);
            }
        });

        lblrv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv.setForeground(new java.awt.Color(102, 102, 102));
        lblrv.setText("Registro");
        lblrv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrvMouseExited(evt);
            }
        });

        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion72.png"))); // NOI18N
        proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedorMouseExited(evt);
            }
        });

        lblrv1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv1.setForeground(new java.awt.Color(102, 102, 102));
        lblrv1.setText("de ventas");
        lblrv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrv1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrv1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcat)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblrv1)
                                .addComponent(lblrv)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblv)
                                    .addComponent(venta)
                                    .addComponent(registro)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbcliente)
                                .addComponent(cliente))
                            .addComponent(categoria, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(proveedor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblp)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblp)
                .addGap(18, 18, 18)
                .addComponent(cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcat)
                .addGap(18, 18, 18)
                .addComponent(venta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblv)
                .addGap(18, 18, 18)
                .addComponent(registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv1)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));
        jPanel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel6PropertyChange(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtPrecioActual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtPrecioActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioActualKeyTyped(evt);
            }
        });

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        btGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        lblPrecioActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        lblStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        lblCboxCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        cboxCategorias.setBorder(null);

        cboxProveedores.setBorder(null);

        lblCboxProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exc.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Proveedor");

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Categoría");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrecioActual, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblPrecioActual)
                            .addComponent(lblStock)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxProveedores, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxCategorias, javax.swing.GroupLayout.Alignment.LEADING, 0, 285, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCboxCategoria)
                            .addComponent(lblCboxProveedor)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecioActual)
                    .addComponent(lblPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cboxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addComponent(lblCboxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCboxCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupaRosa.png"))); // NOI18N

        txtBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btAceptar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btAceptar.setForeground(new java.awt.Color(102, 102, 102));
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btEditar.setForeground(new java.awt.Color(102, 102, 102));
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btEliminar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btEliminar.setForeground(new java.awt.Color(102, 102, 102));
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Precio Actual", "Stock", "Id proveedor", "Id categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homeBlanco.png"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblpMouseEntered

    private void lblpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblpMouseExited

    private void clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseEntered
        cliente.setIcon(new ImageIcon("imagenes\\cliente72n.png"));
        lbcliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_clienteMouseEntered

    private void clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseExited
        cliente.setIcon(new ImageIcon("imagenes\\clientes72.png"));
        lbcliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_clienteMouseExited

    private void lbclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbclienteMouseEntered
        cliente.setIcon(new ImageIcon("imagenes\\cliente72n.png"));
        lbcliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbclienteMouseEntered

    private void lbclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbclienteMouseExited
        cliente.setIcon(new ImageIcon("imagenes\\clientes72.png"));
        lbcliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_lbclienteMouseExited

    private void categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\botella72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_categoriaMouseEntered

    private void categoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\botella72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_categoriaMouseExited

    private void lblcatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\botella72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblcatMouseEntered

    private void lblcatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\botella72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblcatMouseExited

    private void ventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseEntered
        venta.setIcon(new ImageIcon("imagenes\\ticket72n.png"));
        lblv.setForeground(Color.BLACK);
    }//GEN-LAST:event_ventaMouseEntered

    private void ventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseExited
        venta.setIcon(new ImageIcon("imagenes\\ticket72.png"));
        lblv.setForeground(Color.GRAY);
    }//GEN-LAST:event_ventaMouseExited

    private void lblvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseEntered
        venta.setIcon(new ImageIcon("imagenes\\ticket72n.png"));
        lblv.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblvMouseEntered

    private void lblvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseExited
        venta.setIcon(new ImageIcon("imagenes\\ticket72.png"));
        lblv.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblvMouseExited

    private void registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_registroMouseEntered

    private void registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_registroMouseExited

    private void registroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMousePressed

    }//GEN-LAST:event_registroMousePressed

    private void lblrvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrvMouseEntered

    private void lblrvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrvMouseExited

    private void proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_proveedorMouseEntered

    private void proveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_proveedorMouseExited

    private void lblrv1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseEntered
        registro.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrv1MouseEntered

    private void lblrv1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseExited
        registro.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrv1MouseExited

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jPanel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6PropertyChange

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        FrmInicio menu = new FrmInicio();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x.setIcon(new ImageIcon("imagenes\\homeNegro.png"));
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x.setIcon(new ImageIcon("imagenes\\homeBlanco.png"));
    }//GEN-LAST:event_xMouseExited

    private void xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKeyPressed

    }//GEN-LAST:event_xKeyPressed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        if (this.txtId.getText().isEmpty() || this.txtId.getText().equals("")) {
            this.guardarProducto();
        } else {
            this.actualizarProducto();
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        this.buscarLike();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        this.cargarProducto();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        this.eliminar();
    }//GEN-LAST:event_btEliminarActionPerformed

    private void proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_proveedorMouseClicked

    private void lblpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_lblpMouseClicked

    private void categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_categoriaMouseClicked

    private void lblcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseClicked
        if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblcatMouseClicked

    private void ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ventaMouseClicked

    private void lblvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvMouseClicked
        if (!hayCliente()) {
            if (!hayVenta()) {
                FrmVenta v = new FrmVenta();
                this.dispose();
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ninguna venta registrada", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblvMouseClicked

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_registroMouseClicked

    private void lblrvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrvMouseClicked

    private void lblrv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrv1MouseClicked

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_clienteMouseClicked

    private void lbclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbclienteMouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_lbclienteMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() == 100) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        if (txtStock.getText().length() == 11) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecioActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioActualKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtPrecioActual.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioActualKeyTyped

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        if (txtBusqueda.getText().length() == 15) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar())) {
            if (!Character.isLetter(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private boolean hayProducto() {
        List<Producto> listaProductos = controlProductos.buscarTodas("");
        if (listaProductos.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayVenta() {
        List<Venta> listaVentas = controlVentas.buscarTodas("");
        if (listaVentas.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayProveedor() {
        List<Proveedor> listaProveedores = controlProveedores.buscarTodas("");
        if (listaProveedores.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCliente() {
        List<Cliente> listaClientes = controlClientes.buscarTodas("");
        if (listaClientes.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCategoria() {
        List<Categoria> listaCategoria = controlCategorias.buscarTodas("");
        if (listaCategoria.isEmpty()) {
            return true;
        }
        return false;
    }

    private void guardarProducto() {
        if (!camposVacios()) {
            String nombre = this.txtNombre.getText();
            float precioActual = Float.parseFloat(this.txtPrecioActual.getText());
            int stock = Integer.parseInt(this.txtStock.getText());
            Categoria categoria = (Categoria) this.cboxCategorias.getSelectedItem();
            Proveedor proveedor = (Proveedor) this.cboxProveedores.getSelectedItem();
            Producto producto = new Producto(nombre, precioActual, stock, proveedor, categoria);
            if (Integer.parseInt(this.txtStock.getText()) > 0) {
                if (controlProductos.guardar(producto)) {
                    JOptionPane.showMessageDialog(this, "Producto guardado correctamente.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarCampos();
                    this.llenarTablasProductos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar la categoría.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de stock no puede ser menor que 1.",
                        "Precaución", JOptionPane.WARNING_MESSAGE);
                this.lblStock.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos deben de estar llenos.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void actualizarProducto() {
        if (!camposVacios()) {
            int id = Integer.parseInt(this.txtId.getText());
            String nombre = this.txtNombre.getText();
            float precioActual = Float.parseFloat(this.txtPrecioActual.getText());
            int stock = Integer.parseInt(this.txtStock.getText());
            Categoria categoria = (Categoria) this.cboxCategorias.getSelectedItem();
            Proveedor proveedor = (Proveedor) this.cboxProveedores.getSelectedItem();
            Producto producto = new Producto(id, nombre, precioActual, stock, proveedor, categoria);
            if (Integer.parseInt(this.txtStock.getText()) > 0) {
                if (controlProductos.actualizar(producto)) {
                    JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarCampos();
                    this.llenarTablasProductos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizado la categoría.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de stock no puede ser menor que 1.",
                        "Precaución", JOptionPane.WARNING_MESSAGE);
                this.lblStock.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos deben de estar llenos.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void eliminar() {
        int fila = this.tblProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto.",
                    "Advertecia", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblProductos.getModel();
            int idProducto = (Integer) modelo.getValueAt(fila, 0);
            int stock = (Integer) modelo.getValueAt(fila, 3);
            if (controlProductos.eliminar(idProducto)) {
                JOptionPane.showMessageDialog(this, "Producto Eliminado exitosamente",
                        "Hecho", JOptionPane.INFORMATION_MESSAGE);
                this.llenarTablasProductos();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido eliminar el producto.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void buscarLike() {
        String Busqueda = txtBusqueda.getText();
        listaProductos = controlProductos.buscarLike(Busqueda);
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (Producto producto : listaProductos) {
            modelo.addRow(producto.toArray());
        }
    }

    private void cargarProducto() {
        int fila = this.tblProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto.",
                    "Precaución", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblProductos.getModel();
            Integer idProducto = (Integer) modelo.getValueAt(fila, 0);
            Producto producto = controlProductos.buscarporID(idProducto);
            if (producto != null) {
                this.txtId.setText(String.valueOf(producto.getIdproducto()));
                this.txtNombre.setText(producto.getNombre());
                this.txtPrecioActual.setText(String.valueOf(producto.getprecioactual()));
                this.txtStock.setText(String.valueOf(producto.getStock()));
                this.cboxCategorias.setSelectedItem(producto.getCategoria());
                this.cboxProveedores.setSelectedItem(producto.getProveedor());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el producto.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void llenarTablasProductos() {
        String Busqueda = txtBusqueda.getText();
        this.listaProductos = controlProductos.buscarTodas(Busqueda);
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
        for (Producto producto : listaProductos) {
            modelo.addRow(producto.toArray());
        }
    }

    private void llenarCboxProveedores() {
        Proveedor seleccioneP = new Proveedor();
        seleccioneP.setIdproveedor(0);
        seleccioneP.setNombre("Seleccione...");
        cboxProveedores.addItem(seleccioneP);
        List<Proveedor> proveedores = this.controlProveedores.buscarTodas("");
        for (Proveedor proveedor : proveedores) {
            cboxProveedores.addItem(proveedor);
        }
    }

    private void llenarCboxCategorias() {
        Categoria seleccioneC = new Categoria();
        seleccioneC.setIdcategoria(0);
        seleccioneC.setNombre("Seleccione...");
        cboxCategorias.addItem(seleccioneC);
        List<Categoria> categorias = this.controlCategorias.buscarTodas("");
        for (Categoria categoria : categorias) {
            cboxCategorias.addItem(categoria);
        }
    }

    private boolean camposVacios() {
        boolean hayVacios = false;
        if (this.txtNombre.getText().isEmpty() || this.txtNombre.equals("")) {
            hayVacios = true;
            this.lblNombre.setVisible(true);
        } else {
            this.lblNombre.setVisible(false);
        }
        if (this.txtPrecioActual.getText().isEmpty() || this.txtPrecioActual.getText().equals("")) {
            hayVacios = true;
            this.lblPrecioActual.setVisible(true);
        } else {
            this.lblPrecioActual.setVisible(false);
        }
        if (this.txtStock.getText().isEmpty() || this.txtStock.getText().equals("")) {
            hayVacios = true;
            this.lblStock.setVisible(true);
        } else if (Integer.parseInt(this.txtStock.getText()) > 0) {
            this.lblStock.setVisible(false);
        }
        if (this.cboxProveedores.getSelectedIndex() == 0) {
            hayVacios = true;
            this.lblCboxProveedor.setVisible(true);
        } else {
            this.lblCboxProveedor.setVisible(false);
        }
        if (this.cboxCategorias.getSelectedIndex() == 0) {
            hayVacios = true;
            this.lblCboxCategoria.setVisible(true);
        } else {
            this.lblCboxCategoria.setVisible(false);
        }
        return hayVacios;
    }

    private void quitarAdvertencias() {
        this.lblNombre.setVisible(false);
        this.lblPrecioActual.setVisible(false);
        this.lblStock.setVisible(false);
        this.lblCboxProveedor.setVisible(false);
        this.lblCboxCategoria.setVisible(false);
    }

    private void limpiarCampos() {
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtPrecioActual.setText("");
        this.txtStock.setText("0");
        this.cboxCategorias.setSelectedIndex(0);
        this.cboxProveedores.setSelectedIndex(0);
        this.txtBusqueda.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel categoria;
    private javax.swing.JComboBox<Categoria> cboxCategorias;
    private javax.swing.JComboBox<Proveedor> cboxProveedores;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lblCboxCategoria;
    private javax.swing.JLabel lblCboxProveedor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioActual;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblcat;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel lblrv;
    private javax.swing.JLabel lblrv1;
    private javax.swing.JLabel lblv;
    private javax.swing.JLabel proveedor;
    private javax.swing.JLabel registro;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioActual;
    private javax.swing.JTextField txtStock;
    private javax.swing.JLabel venta;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
