/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Control.ControlCategorias;
import Control.ControlCliente;
import Control.ControlProductos;
import Control.ControlProveedores;
import Control.ControlVenta;
import com.github.lgooddatepicker.components.DatePicker;
import java.awt.Color;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.Categoria;
import objetosNegocio.Cliente;
import objetosNegocio.Producto;
import objetosNegocio.Proveedor;
import objetosNegocio.Rel_ProductoVenta;
import objetosNegocio.Venta;

/**
 *
 * @author miran
 */
public class FrmVenta extends javax.swing.JFrame {

    private ControlCategorias controlCategorias;
    private ControlProductos controlProductos;
    private ControlProveedores controlProveedores;
    private ControlCliente controlClientes;
    private ControlVenta controlVentas;
    private List<Venta> listaVentas;
    private List<Producto> listaProductos;
    private List<Rel_ProductoVenta> listaRelacionPV;

    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
        this.setTitle("FrmVenta");
        this.setLocationRelativeTo(null);
        this.controlProveedores = new ControlProveedores();
        this.controlCategorias = new ControlCategorias();
        this.controlClientes = new ControlCliente();
        this.controlVentas = new ControlVenta();
        this.controlProductos = new ControlProductos();
        this.listaVentas = new ArrayList<>();
        this.listaProductos = new ArrayList<>();
        this.listaRelacionPV = new ArrayList<>();
        this.llenarCboxClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblp = new javax.swing.JLabel();
        producto = new javax.swing.JLabel();
        lblpro = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        lblcat = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        ventas = new javax.swing.JLabel();
        proveedor = new javax.swing.JLabel();
        lblrv = new javax.swing.JLabel();
        lblrv1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSubtotal = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtIdventa = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cBoxCliente = new javax.swing.JComboBox<>();
        dtpDesde = new com.github.lgooddatepicker.components.DateTimePicker();
        dtpHasta = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        lblp.setText("Proveedores");
        lblp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblp.setForeground(new java.awt.Color(102, 102, 102));
        lblp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpMouseExited(evt);
            }
        });

        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canasta72.png"))); // NOI18N
        producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productoMouseExited(evt);
            }
        });

        lblpro.setText("Productos");
        lblpro.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblpro.setForeground(new java.awt.Color(102, 102, 102));
        lblpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblproMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblproMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblproMouseExited(evt);
            }
        });

        categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botella72.png"))); // NOI18N
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriaMouseExited(evt);
            }
        });

        lblcat.setText("Categorias");
        lblcat.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblcat.setForeground(new java.awt.Color(102, 102, 102));
        lblcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcatMouseExited(evt);
            }
        });

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes72.png"))); // NOI18N
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteMouseExited(evt);
            }
        });

        lblcliente.setText("Clientes");
        lblcliente.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblcliente.setForeground(new java.awt.Color(102, 102, 102));
        lblcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblclienteMouseExited(evt);
            }
        });

        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito72.png"))); // NOI18N
        ventas.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ventas.setToolTipText("");
        ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ventasMousePressed(evt);
            }
        });

        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camion72.png"))); // NOI18N
        proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedorMouseExited(evt);
            }
        });

        lblrv.setText("Registro");
        lblrv.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv.setForeground(new java.awt.Color(102, 102, 102));
        lblrv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrvMouseExited(evt);
            }
        });

        lblrv1.setText("de ventas");
        lblrv1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblrv1.setForeground(new java.awt.Color(102, 102, 102));
        lblrv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrv1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblrv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblrv1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(producto))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(categoria))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblcat))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcliente)
                                    .addComponent(cliente)
                                    .addComponent(ventas)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblpro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblrv1)
                                    .addComponent(lblrv))
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(proveedor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblp)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblp)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpro)
                .addGap(18, 18, 18)
                .addComponent(categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcat)
                .addGap(18, 18, 18)
                .addComponent(cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcliente)
                .addGap(18, 18, 18)
                .addComponent(ventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrv1)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));
        jPanel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel6PropertyChange(evt);
            }
        });

        txtSubtotal.setEditable(false);
        txtSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sub total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        txtDescuento.setEditable(false);
        txtDescuento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descuento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });

        txtMonto.setEditable(false);
        txtMonto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monto total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        txtIdventa.setEditable(false);
        txtIdventa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        txtNombre.setEditable(false);
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtIdventa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));

        btBuscar.setText("Buscar");
        btBuscar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(102, 102, 102));
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Venta", "Cliente", "Fecha y hora", "Sub total", "Descuento", "Monto total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        jLabel6.setText("Fechas y horas");
        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));

        dtpDesde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dtpHasta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setText("Cliente");
        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(dtpDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtpHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtpDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Detalles de venta");
        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 102));

        jLabel4.setText("Buscador de ventas");
        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 2));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id producto", "Nombre", "Precio actual", "Cantidad", "Monto total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setText("Productos");
        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homeBlanco.png"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xKeyPressed(evt);
            }
        });

        jLabel1.setText("Ventas");
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(x)))
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblpMouseEntered

    private void lblpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblpMouseExited

    private void productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseEntered
        producto.setIcon(new ImageIcon("imagenes\\canasta72n.png"));
        lblpro.setForeground(Color.BLACK);
    }//GEN-LAST:event_productoMouseEntered

    private void productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseExited
        producto.setIcon(new ImageIcon("imagenes\\canasta72.png"));
        lblpro.setForeground(Color.GRAY);
    }//GEN-LAST:event_productoMouseExited

    private void lblproMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseEntered
        producto.setIcon(new ImageIcon("imagenes\\canasta72n.png"));
        lblpro.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblproMouseEntered

    private void lblproMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseExited
        producto.setIcon(new ImageIcon("imagenes\\canasta72.png"));
        lblpro.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblproMouseExited

    private void categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\botella72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_categoriaMouseEntered

    private void categoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\botella72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_categoriaMouseExited

    private void lblcatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseEntered
        categoria.setIcon(new ImageIcon("imagenes\\botella72n.png"));
        lblcat.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblcatMouseEntered

    private void lblcatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseExited
        categoria.setIcon(new ImageIcon("imagenes\\botella72.png"));
        lblcat.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblcatMouseExited

    private void clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseEntered
        cliente.setIcon(new ImageIcon("imagenes\\cliente72n.png"));
        lblcliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_clienteMouseEntered

    private void clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseExited
        cliente.setIcon(new ImageIcon("imagenes\\clientes72.png"));
        lblcliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_clienteMouseExited

    private void lblclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseEntered
        cliente.setIcon(new ImageIcon("imagenes\\cliente72n.png"));
        lblcliente.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblclienteMouseEntered

    private void lblclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseExited
        cliente.setIcon(new ImageIcon("imagenes\\clientes72.png"));
        lblcliente.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblclienteMouseExited

    private void ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseEntered
        ventas.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_ventasMouseEntered

    private void ventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseExited
        ventas.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_ventasMouseExited

    private void ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMousePressed

    }//GEN-LAST:event_ventasMousePressed

    private void proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseEntered
        proveedor.setIcon(new ImageIcon("imagenes\\camion72n.png"));
        lblp.setForeground(Color.BLACK);
    }//GEN-LAST:event_proveedorMouseEntered

    private void proveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseExited
        proveedor.setIcon(new ImageIcon("imagenes\\camion72.png"));
        lblp.setForeground(Color.GRAY);
    }//GEN-LAST:event_proveedorMouseExited

    private void jPanel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6PropertyChange

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        FrmInicio menu = new FrmInicio();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
          x.setIcon(new ImageIcon("imagenes\\homeNegro.png"));
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
         x.setIcon(new ImageIcon("imagenes\\homeBlanco.png"));
    }//GEN-LAST:event_xMouseExited

    private void xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKeyPressed

    }//GEN-LAST:event_xKeyPressed

    private void lblrvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseEntered
        ventas.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrvMouseEntered

    private void lblrvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseExited
        ventas.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrvMouseExited

    private void lblrv1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseEntered
        ventas.setIcon(new ImageIcon("imagenes\\carrito72n.png"));
        lblrv.setForeground(Color.BLACK);
        lblrv1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblrv1MouseEntered

    private void lblrv1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseExited
        ventas.setIcon(new ImageIcon("imagenes\\carrito72.png"));
        lblrv.setForeground(Color.GRAY);
        lblrv1.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblrv1MouseExited

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_proveedorMouseClicked

    private void lblpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpMouseClicked
        FrmProveedor p = new FrmProveedor();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_lblpMouseClicked

    private void productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_productoMouseClicked

    private void lblproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproMouseClicked
        if (!hayCategoria()) {
            if (!hayProveedor()) {
                FrmProducto producto = new FrmProducto();
                this.dispose();
                producto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ninguna categoria registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblproMouseClicked

    private void categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseClicked
       if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado registrada", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_categoriaMouseClicked

    private void lblcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcatMouseClicked
       if (!hayCliente()) {
            if (!hayProveedor()) {
                FrmCategoria cat = new FrmCategoria();
                this.dispose();
                cat.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún proveedor registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningun cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblcatMouseClicked

    private void ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ventasMouseClicked

    private void lblrvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrvMouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrvMouseClicked

    private void lblrv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrv1MouseClicked
        if (!hayCliente()) {
            if (!hayProducto()) {
                FrmRegistroVenta rv = new FrmRegistroVenta();
                this.dispose();
                rv.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No existe ningún producto registrado", "Información", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe ningún cliente registrado", "Información", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblrv1MouseClicked

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_clienteMouseClicked

    private void lblclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclienteMouseClicked
        FrmCliente c = new FrmCliente();
        this.dispose();
        c.setVisible(true);
    }//GEN-LAST:event_lblclienteMouseClicked

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarMouseClicked

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        this.limpiarCampos();
        this.llenarTablaVentas();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        if (evt.getClickCount() >= 2) {
            this.llenarTablaProductos();
        }
    }//GEN-LAST:event_tblVentasMouseClicked

    private boolean hayProducto() {
        List<Producto> listaProductos = controlProductos.buscarTodas("");
        if (listaProductos.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayVenta() {
        List<Venta> listaVentas = controlVentas.buscarTodas("");
        if (listaVentas.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayProveedor() {
        List<Proveedor> listaProveedores = controlProveedores.buscarTodas("");
        if (listaProveedores.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCliente() {
        List<Cliente> listaClientes = controlClientes.buscarTodas("");
        if (listaClientes.isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean hayCategoria() {
        List<Categoria> listaCategoria = controlCategorias.buscarTodas("");
        if (listaCategoria.isEmpty()) {
            return true;
        }
        return false;
    }

    private void llenarCboxClientes() {
        Cliente seleccioneC = new Cliente();
        seleccioneC.setIdcliente(0);
        seleccioneC.setNombre("Todos");
        cBoxCliente.addItem(seleccioneC);
        List<Cliente> clientes = this.controlClientes.buscarTodas("");
        for (Cliente cliente : clientes) {
            cBoxCliente.addItem(cliente);
        }
    }

    private void llenarTablaVentas() {
        Cliente cliente = (Cliente) this.cBoxCliente.getSelectedItem();
        LocalDateTime desde = this.dtpDesde.getDateTimePermissive();
        Date fechaDesde = Date.from(desde.atZone(ZoneId.systemDefault()).toInstant());
        LocalDateTime hasta = this.dtpHasta.getDateTimePermissive();
        Date fechaHasta = Date.from(hasta.atZone(ZoneId.systemDefault()).toInstant());
        listaVentas = controlVentas.busquedaRango(cliente, fechaDesde, fechaHasta);
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        modelo.setRowCount(0);
        for (Venta venta : listaVentas) {
            Object[] detalle = new Object[6];
            detalle[0] = venta.getIdventa();
            detalle[1] = venta.getCliente().getNombre();
            detalle[2] = venta.getFecha();
            detalle[3] = venta.getDescuento() + venta.getMontoFinal();
            detalle[4] = venta.getDescuento();
            detalle[5] = venta.getMontoFinal();
            modelo.addRow(detalle);
        }
    }

    private void llenarTablaProductos() {
        int fila = this.tblVentas.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        DefaultTableModel modeloSeleccionado = (DefaultTableModel) tblProductos.getModel();
        int id = (Integer) modelo.getValueAt(fila, 0);
        modeloSeleccionado.setRowCount(0);
        Venta venta = this.buscarEnLista(id);
        String idVenta = String.valueOf(venta.getIdventa());
        this.txtIdventa.setText(idVenta);
        String nombre = venta.getCliente().getNombre();
        this.txtNombre.setText(nombre);
        String descuento = String.valueOf(venta.getDescuento());
        this.txtDescuento.setText(descuento);
        String montoTotal = String.valueOf(venta.getMontoFinal());
        this.txtMonto.setText(montoTotal);
        float subTotal = venta.getDescuento() + venta.getMontoFinal();
        String subTot = String.valueOf(subTotal);
        this.txtSubtotal.setText(subTot);
        this.listaRelacionPV = venta.getRelProVen();
        System.out.println(listaRelacionPV.size());
        for (Rel_ProductoVenta relacion : listaRelacionPV) {
            Object[] detalle = new Object[5];
            detalle[0] = relacion.getProducto().getIdproducto();
            detalle[1] = relacion.getProducto().getNombre();
            detalle[2] = relacion.getProducto().getprecioactual();
            detalle[3] = relacion.getCantidad();
            detalle[4] = relacion.getProducto().getprecioactual() * relacion.getCantidad();

            modeloSeleccionado.addRow(detalle);
        }
    }

    private Venta buscarEnLista(int id) {
        for (Venta venta : listaVentas) {
            if (venta.getIdventa() == id) {
                return venta;
            }
        }
        return null;
    }

    private void limpiarCampos() {
        DefaultTableModel modeloSeleccionado = (DefaultTableModel) tblProductos.getModel();
        modeloSeleccionado.setRowCount(0);
        this.txtDescuento.setText("");
        this.txtMonto.setText("");
        this.txtSubtotal.setText("");
        this.txtIdventa.setText("");
        this.txtNombre.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JComboBox<Cliente> cBoxCliente;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel cliente;
    private com.github.lgooddatepicker.components.DateTimePicker dtpDesde;
    private com.github.lgooddatepicker.components.DateTimePicker dtpHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcat;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel lblpro;
    private javax.swing.JLabel lblrv;
    private javax.swing.JLabel lblrv1;
    private javax.swing.JLabel producto;
    private javax.swing.JLabel proveedor;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIdventa;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JLabel ventas;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
